LEVERAGE_CONFIG = {
    "BTCUSDT": 50,
    "ETHUSDT": 50,
    "SOLUSDT": 20,
    "XRPUSDT": 20,
    "ADAUSDT": 20,
    "JASMYUSDT": 50,
    "APEUSDT": 50,
    "DEXEUSDT": 20,
    "FARTCOINUSDT": 75,
    "YFIUSDT": 25,
    "ETCUSDT": 50,
    "ZROUSDT": 25,
    "PENGUUSDT": 75,
    "ILVUSDT": 20,
    "MAGICUSDT": 25,
    "DOGEUSDT": 75,
    "DEEPUSDT": 25,
    "ICXUSDT": 25,
    # Add more as needed
}
